apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.product_name }}
  annotations:
    ingress.kubernetes.io/ssl-redirect: "{{ .Values.networking.ssl_redirect }}"
spec:
  rules:
  - http:
      paths:
      - path: /helm.html
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.product_name }}
            port:
              number: {{ .Values.networking.ingrees_port }}
