apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.product_name }}-secrets
type: Opaque
stringData:
  USER_NAME: {{ .Values.product_name }}
{{ if empty .Values.PASSWORD }}
  #Create Random Password
  PASSWORD: {{ randAlphaNum 32 | b64enc | quote }}
{{ else }}
  PASSWORD: {{ .Values.PASSWORD }}
{{ end }}