apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.product_name }}
spec:
  selector:
    app: {{ .Values.product_name }}
  ports:
  - protocol: TCP
    port: {{ .Values.networking.service_port }}
    targetPort: http
    name: http
